const list = await (await fetch('http://127.0.0.1:9222/json')).json();
const page = list.find((t) => t.type === 'page' && t.url.startsWith('http://127.0.0.1:3081'));
const ws = new WebSocket(page.webSocketDebuggerUrl);
const pend = new Map(); let id = 0;
ws.onmessage = (e) => { const m = JSON.parse(e.data); if (m.id && pend.has(m.id)) { pend.get(m.id)(m); pend.delete(m.id); } };
await new Promise((r) => (ws.onopen = r));
const send = (m, p = {}) => new Promise((r) => { const i = ++id; pend.set(i, r); ws.send(JSON.stringify({ id: i, method: m, params: p })); });
const ev = async (x) => (await send('Runtime.evaluate', { expression: x, returnByValue: true })).result?.result?.value;
await send('Runtime.enable'); await send('Page.enable'); await send('Network.enable');
await send('Network.setCacheDisabled', { cacheDisabled: true });
await send('Page.reload'); await new Promise((r) => setTimeout(r, 11000));
console.log('footer ★ buttons:', await ev(`[...document.querySelectorAll('button')].filter(b=>(b.textContent||'').trim()==='★' && b.title).length`));
await ev(`document.dispatchEvent(new KeyboardEvent('keydown',{ctrlKey:true,key:'k',bubbles:true}))`);
await new Promise((r) => setTimeout(r, 1200));
console.log('palette rows:', JSON.stringify(await ev(`(()=>{const p=document.querySelector('.dshome-palette');if(!p)return [];const c=p.children[0].children[1];return [...c.children].slice(0,5).map(x=>(x.children[0]?.textContent||'').slice(0,40))})()`)));
console.log('palette open:', await ev(`(()=>{const p=document.querySelector('.dshome-palette');return p?getComputedStyle(p).display:null})()`));
ws.close(); process.exit(0);
