const list = await (await fetch('http://127.0.0.1:9222/json')).json();
const page = list.find((t) => t.type === 'page' && t.url.startsWith('http://127.0.0.1:3081'));
const ws = new WebSocket(page.webSocketDebuggerUrl);
const pend = new Map(); let id = 0;
ws.onmessage = (e) => { const m = JSON.parse(e.data); if (m.id && pend.has(m.id)) { pend.get(m.id)(m); pend.delete(m.id); } };
await new Promise((r) => (ws.onopen = r));
const send = (method, params = {}) => new Promise((r) => { const i = ++id; pend.set(i, r); ws.send(JSON.stringify({ id: i, method, params })); });
const ev = async (x) => (await send('Runtime.evaluate', { expression: x, returnByValue: true, awaitPromise: true })).result?.result?.value;
await send('Runtime.enable');
await ev(`document.querySelector('[aria-haspopup="dialog"]')?.click()`);
await new Promise((r) => setTimeout(r, 1500));
console.log('nav labels:', JSON.stringify(await ev(`(()=>{const nav=document.querySelector('[role="dialog"] nav')||document.querySelector('[role="dialog"]');const b=[...nav.querySelectorAll('button')].map(x=>(x.textContent||'').trim()).filter(Boolean);return b})()`)));
ws.close(); process.exit(0);
