const list = await (await fetch('http://127.0.0.1:9222/json')).json();
const page = list.find((t) => t.type === 'page' && t.url.startsWith('http://127.0.0.1:3081'));
const ws = new WebSocket(page.webSocketDebuggerUrl);
const pend = new Map(); let id = 0;
ws.onmessage = (e) => { const m = JSON.parse(e.data); if (m.id && pend.has(m.id)) { pend.get(m.id)(m); pend.delete(m.id); } };
await new Promise((r) => (ws.onopen = r));
const send = (method, params = {}) => new Promise((r) => { const i = ++id; pend.set(i, r); ws.send(JSON.stringify({ id: i, method, params })); });
const ev = async (x) => (await send('Runtime.evaluate', { expression: x, returnByValue: true, awaitPromise: true })).result?.result?.value;
await send('Runtime.enable');
await send('Network.enable');
await send('Network.setCacheDisabled', { cacheDisabled: true });
await send('Page.enable');
await send('Page.reload', { ignoreCache: true });
await new Promise((r) => setTimeout(r, 5000));
await ev(`document.querySelector('[aria-haspopup="dialog"]')?.click()`);
await new Promise((r) => setTimeout(r, 1200));
await ev(`(()=>{const c=[...document.querySelectorAll('button')].find(b=>(b.textContent||'').trim()==='插件管理');c&&c.click();return !!c})()`);
await new Promise((r) => setTimeout(r, 800));
// click the 市场 tab
await ev(`(()=>{const c=[...document.querySelectorAll('button')].find(b=>(b.textContent||'').trim()==='市场');c&&c.click();return !!c})()`);
await new Promise((r) => setTimeout(r, 2500));
console.log('market header:', await ev(`document.body.innerText.includes('目录源')`));
console.log('source rows (启用 buttons):', await ev(`(()=>{const b=[...document.querySelectorAll('button')].filter(x=>(x.textContent||'').trim()==='启用');return b.length})()`));
console.log('source names:', JSON.stringify(await ev(`(()=>{const t=document.body.innerText;const m=t.match(/DSH 1024[^\n]*|dshfind[^\n]*|DeepSeek[^\n]*/g);return m?m.slice(0,6):[]})()`)));
ws.close(); process.exit(0);
